# Welcome to Jekyll!
# This config file is meant for settings that affect your whole blog

# Main Page Setup
title: Shodhan Kumar Shetty's Portfolio

# Hero Section
name: Shodhan Kumar Shetty
headline: Final Year CSE Student | Java Developer | Data Analytics Enthusiast
description: >-
  A final year Computer Science Engineering student at Alva’s Institute of Engineering and Technology.
  Strong interest in Java programming and problem solving involving arrays, strings, numericals, sliding window,
  and hashtable-based approaches. Also exploring data analytics using PostgreSQL and web development.

profile_image: ./assets/images/profile-image/pfp.jpg

resume-url: https://drive.google.com/file/d/13Z3duVzh-gguPU5r03oJVEE6rV9rd3DS/view?usp=sharing

# External links
external-links:
  linkedin: shodhan-kumar-shetty-182568252
  github: shodhanshetty12
  leetcode: CtrlAltConquer
  codechef: shodhanshetty
  hackerank: 4AL22CS150
  youtube: shodhanshetty12
  medium: shodhankumarshetty963
  discord: channels/1394703412943126540/1394703413555499201
  bluesky: shodhankumarshetty.bsky.social

# Skills Section
skills:
  - category: Programming Languages
    tools:
    - Java
    - Python
    - C
    - C++
  - category: Data Analytics & Databases
    tools:
    - PostgreSQL
    - MySQL
    - Pandas
    - Excel
  - category: Web & Software Development
    tools:
    - React.js
    - Jupyter Notebook
    - Eclipse IDE
    - VS Code
  - category: Documentation & CAD Tools
    tools:
    - TeXworks
    - Solid Edge CAD
  - category: Cloud & Platforms
    tools:
    - AWS
    - Google Cloud
    - HackerRank
    - LeetCode
    - CodeChef
    - GeeksforGeeks
    - Coursera
    - Udemy
    - Infosys Springboard

# Contact Form Setup
formspree-key: https://formspree.io/f/{8-digit key}

# Theme Colors
colors:
  text: "#1a1c20"
  border: "#ddd"
  link: "#4a76ee"
  highlight: "#0c0cf2"
  background: "#ffffff"
  light_background: "#f3f5fb"

# Build settings
collections:
  projects:
    output: true
    permalink: /projects/:path/

markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
      indent: 0

plugins:
  - jekyll-feed

include:
  - _projects
